### PR TITLE
Added new method

### PR DESCRIPTION
**Pull request by kikoseijo**
Added a search using like, have also PSR2 the file to pass CI-Style.

### CODE REVIEW

**Comment by OzanKurt** [comment]
If there were an option to paginate the results. That should be done in all possible methods. I will be looking into that.

**Comment by kikoseijo** [comment]
What i don't get to understand its the Criterion, its not clear the use of it.
Regarding the pagination method, have looked at this? https://github.com/OzanKurt/Repoist/pull/24/commits/7ae3ff92ae31959f4b8e1e512ebe875bdc738e05
Because another option is to add some flags to the class, but for this we will need to set the flag, and will only be used in couple methods, rest don't need them, just in the all, and search.

What im doing its call directly your entity and use from there.

We can look how others are doing, and find best solution.

Before your library i was building all this methods in each repo, but now i only have to write couple, only that its quite time saving, so to make it more powerful could be an option but i don't see as a need.

I have worked with your library just couple days, with more use ill be able to find a pattern, and find best option.

What you think on?

**Comment by OzanKurt** [comment]
Exactly! Lets play with the code a little, maybe we can try adding an another function for pagination. So that people who needs custom methods won't replicate their code. 

I'm hoping to merge when I have time to do it properly.

**Comment by kikoseijo** [comment]
Excellent,

Another idea:

```php
public function withRelationships(array $relationships, $paginate = 0)
    {
        // We should make some checks before getting to this
        $records = $this->entity->with($relationships);

        return $paginate>0 ? $records->paginate($paginate) : $records->get();
    }
```

Another possibility could be to make functions with more params, but I like it simple, as you have it.

This is an example of how the controllers are ending, before I was doing the validation in the Resource Controller and the rest of the work in the Repo, now Im doing the extra fields in controller before update or create:

```php
<?php

namespace App\Http\Controllers\Admin;

use App\Contracts\Repositories\PointRepository;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PointController extends Controller
{
    /**
     * @var mixed
     */
    protected $repo;

    /**
     * @param PointRepository $repo
     */
    public function __construct(PointRepository $repo)
    {
        $this->middleware('auth');
        $this->middleware('admin');
        $this->repo = $repo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->repo->withRelationships();
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function search(Request $request)
    {
        $query = $request->input('query');
        $itemsPerPage = 10; // Leave null or 0 to get raw collection
        return $this->repo->findWhereLike('name', '%'.$query.'%', $itemsPerPage);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'question'    => 'required',
            'answer'      => 'required',
            'category_id' => 'required',
        ]);

        $data = $request->all();
        $data['slug'] = str_slug($data['name']);

        $this->repo->create($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'name'    => 'required',
            'latitude'    => 'required',
            'longitude'    => 'required',
        ]);

        $data = $request->all();

        if (!$request->has('slug')) {
            $data['slug'] = str_slug($data['name']);
        }

        $point = $this->repo->find($id);
        $point->update($data);

        \Log::error($point);

        $cats = array_pluck($request->categories, 'id');
        $point->communities()->sync($request->communities);
        $point->categories()->sync($cats);

        \Log::error('Record saved succesfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repo->delete($id);
    }
}

```

To finish this ill like to know ***What the Criteria meant to do?*** just explain the idea when you have some time (No rush), I like what Yajra dataTables its doing in the sense of being able to filter the tables and paginate at same time, but for that feature to work ok they control also how Queries get to the endpoints and know structure of the data when they paint tables.

Anyways, the time I saved this couple of days developing with this lovely library deserves some effort to make it better.

Happy days!

**Comment by OzanKurt** [comment]
The relations are already added as Criterion. I will make a tutorial soon.

**Comment by kikoseijo** [comment]
Got a fix for Lumen, need to be used with absolute path.

**Comment by kikoseijo** [comment]
Wait, not working now.
I just have to upload to github to be able to test it.

**Comment by OzanKurt** [comment]
I will be merging these changes once I have time to check. Thanks :)

**Comment by kikoseijo** [comment]
No, there is no withRelationships, I found a bug on last commit also, you forgot a ! 
;-)

**Pull request merged**
