### PR TITLE
Make it possible to have files generated outside of the app folder

### PR DESCRIPTION
**Pull request by warrickhill**
These changes make it possible to have files generated outside on the app folder.

They also allow namespacing to be as deep as you want something like

```
php artisan make:repository Path/To/The/Very/Deep/Namespace/You/Wanted/File
```

would give a namespace of Path\To\The\Very\Deep\Namespace\You\Wanted in FileRepository.php

### CODE REVIEW

**Comment by OzanKurt** [comment]
Does it work now?

**Comment by warrickhill** [comment]
It works for our needs but I realise now that this would be a breaking change. I have a compatability fix in mind but will not be able to push this for a couple of days.

**Comment by OzanKurt** [comment]
I am thinking abour refactoring my repos, so actually we can make it v2.

**Comment by warrickhill** [comment]
that would work for us. always nice to have a version bump :+1:

**Pull request merged**
